### ISSUE TITLE
CALayer bounds contains NaN: [0 nan; 320 291]

### ISSUE THREAD

**Issue by Shelley-ND** [hackiftekhar/IQDropDownTextField#89] opened 2018-03-13 02:14 UTC
I have a crash problem, and log like this :  

CRASH: CALayer bounds contains NaN: [0 nan; 320 291]
2018-03-12 19:23:13.096676+0800  *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [0 nan; 320 291]'

**Comment by hackiftekhar** [comment] 2018-03-17 09:25
@Shelley-ND Can you please try https://stackoverflow.com/a/42960746/1582217 and let me know more information about this, specially at which line of code it get's crash.

**Comment by hackiftekhar** [comment] 2018-03-17 13:04
Duplicate of #86

**Closed by hackiftekhar** 2018-03-17 13:04 UTC
Labels: duplicate

**Comment by ycwjjjj** [comment] 2021-03-16 02:28
we are using v2.0. but still encounter this CAlayer crash as below. Is it possible to keep on investigate it and fix it? Thanks!

libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [0 nan; 320 291]. Layer: <CALayer:0x283c19480; position = CGPoint (151 16.8333); bounds = CGRect (0 -129.667; 320 291); delegate = <UIPickerTableView: 0x116520200; frame = (-9 -128.667; 320 291); opaque = NO; gestureRecognizers = <NSArray: 0x2832bff30>; layer = <CALayer: 0x283c19480>; contentOffset: {0, -129.66666666666666}; contentSize: {320, 0}; adjustedContentInset: {129.66666666666666, 0, 129.33333333333334, 0}; dataSource: <UIPickerColumnView: 0x1168ae430; frame = (9 0; 302 216); autoresize = W+TM+H; gestureRecognizers = <NSArray: 0x2832ba160>; layer = <CALayer: 0x283c07220>>>; sublayers = (<CALayer: 0x283c4d820>, <CALayer: 0x283c3b3e0>); allowsGroupOpacity = YES; backgroundColor = (null)>'
terminating with uncaught exception of type NSException
(Recorded stack frame)
