### ISSUE TITLE
CALayer bounds contains NaN: [0 nan; 320 291]

### ISSUE THREAD

**Issue by MahmoudMMB** [hackiftekhar/IQDropDownTextField#86] opened 2018-01-24 14:00 UTC
Really This problem annoyed me
Your library is very fantastic but do you can solve this problem
Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [0 nan; 320 291]'
*** First throw call stack:
(0x184ba1d04 0x183df0528 0x184ba1c4c 0x188b986c0 0x188b8a544 0x18e02437c 0x18e031cb0 0x18e0a9258 0x18e8c8044 0x18dff706c 0x18e09c460 0x18e8c74e0 0x18e2db3f8 0x18e8c6780 0x18e8c6b3c 0x18e22d624 0x1020f3434 0x1020f3220 0x1020f3e14 0x10052612c 0x100521ce8 0x100521e70 0x18dfd8f08 0x18dfd8ae0 0x18e15d68c 0x18e07f2d4 0x18e07ef18 0x18e07ee18 0x18dfd6304 0x188b8fec8 0x188b93fa8 0x188b02a98 0x188b28eb4 0x18e23bf38 0x18e9290f8 0x18e921d04 0x184b4a2e8 0x184b4a268 0x184b49af0 0x184b476c8 0x184a67fb8 0x1868fff84 0x18e03c2f4 0x10060d400 0x18458a56c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by hackiftekhar** [comment] 2018-03-16 13:55
I'm not able understand this stack trace @MahmoudMMB . Can you please send me more information?

**Comment by hackiftekhar** [comment] 2018-03-17 09:25
Can you please try https://stackoverflow.com/a/42960746/1582217 and let me know more information about this, specially at which line of code it get's crash.

**Comment by hackiftekhar** [comment] 2018-03-17 13:04
Duplicate of #78

**Closed by hackiftekhar** 2018-03-17 13:04 UTC
