### ISSUE TITLE
CALayerInvalidGeometry; CALayer bounds contains NaN: [...]

### ISSUE THREAD

**Issue by mitulmarsonia** [hackiftekhar/IQDropDownTextField#78] opened 2017-10-12 06:15 UTC
Thank you so much for making wonderful library.

App some time crash. I have attached fabric screen short.

IQDropDownTextField.m line 321
-[IQDropDownTextField setSelectedRow:animated:]

![screen shot 2017-10-12 at 11 37 58 am](https://user-images.githubusercontent.com/10178632/31481660-33e6dbb6-af42-11e7-859f-70fd128c8cca.png)

Thank You.

**Comment by berabhavin** [comment] 2017-10-12 09:17
I am getting same issue. it is random crash can you please help me out for this.

**Comment by hackiftekhar** [comment] 2017-10-12 15:48
Which version of library you are using right now?

**Comment by mitulmarsonia** [comment] 2017-10-12 16:54
@hackiftekhar  v1.1.1

**Comment by hackiftekhar** [comment] 2017-10-12 19:19
Is it happening every-time or happens sometimes? Are you able to reproduce this issue?

**Comment by mitulmarsonia** [comment] 2017-10-12 20:05
Its happens sometimes. we are using UITableView with multiple textfield then it happens.

**Comment by vishalcnz** [comment] 2018-02-11 21:18
Its happen with me as well. Hard to reproduce but it crash quite a few times

**Comment by hackiftekhar** [comment] 2018-03-17 09:27
Can you guys please try https://stackoverflow.com/a/42960746/1582217 and let me know more information about this.

**Comment by Tapaniya25** [comment] 2018-03-29 08:12
Is it solved this problem?

**Comment by hackiftekhar** [comment] 2018-04-06 18:48
You're doing correct when you set

**Comment by hackiftekhar** [comment] 2018-04-06 18:50
You're doing correct when you set It as optional dropdown.

If you can share demo then it would be great.

**Comment by gask** [comment] 2018-04-12 20:57
Meddling with your code I was able to fix this by changing a single line in the code in the method setSelectedRow:animated as below

`- (void)setSelectedRow:(NSInteger)row animated:(BOOL)animated
{
    NSInteger count = ([_itemList count] + 1);
    if (row < count)
    {
        if (self.isOptionalDropDown)
        {
            if (row == IQOptionalTextFieldIndex)
            {
                super.text = @"";
            }
            else
            {
                super.text = (row == 0) ? @"" : [_itemListUI?:_itemList objectAtIndex:row-1];
            }
            if (row >= 0) { [self.pickerView selectRow:row inComponent:0 animated:animated]; }
            else { [self.pickerView selectRow:0 inComponent:0 animated:animated]; }
        }
        else
        {
            super.text = [_itemListUI?:_itemList objectAtIndex:row];
            [self.pickerView selectRow:row inComponent:0 animated:animated];
        }
    }
}`

if the row = -1 in some weird cases, we got the CALayer crash.

**Comment by shadyk** [comment] 2018-04-20 13:15
@hackiftekhar if @gask is correct can u fix it so can u fix it?

**Comment by hackiftekhar** [comment] 2018-04-20 19:09
Btw, do someone have any steps to reproduce this issue? So that after applying this code I can be sure it's get fix.

**Comment by shadyk** [comment] 2018-05-11 16:10
@hackiftekhar it is happening randomly

**Comment by gask** [comment] 2018-05-11 18:51
It is indeed happening randomly. I tried to isolate the bug in one project to send you @hackiftekhar, but I wasn't able to reproduce it in a definite manner.
The issue has something to do with going back and forth in ViewControllers that have the pickerView with mode = textPicker, but it's happening intermittently... :(
All I know is when I used the code above, the bug stopped happening. But I don't know if its a definite solution...

**Comment by hackiftekhar** [comment] 2018-05-12 07:47
Hmm, okay. I'll try to make some changes.

**Comment by sameer4** [comment] 2018-06-12 05:53
Any update on the fix?

**Comment by shadyk** [comment] 2018-06-12 09:52
@sameer4 use @gask fix that he added on Apr 12 .. it has worked with me

**Comment by sameer4** [comment] 2018-06-12 10:59
need to do that in library what if some other developer working on same projects updates the library files??

> 2018-06-12 12:34:54.585860+0500 Equiloco[11637:337328] [1] = -[UIHorseListViewController onClickHorsePlus:] [L:306] ^^ --- onClickHorsePlus
2018-06-12 12:34:54.640928+0500 Equiloco[11637:337328] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [0 nan; 320 291]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106f8f1e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x00000001060a7031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000107004975 +[NSException raise:format:] + 197
	3   QuartzCore                          0x00000001084be065 _ZN2CA5Layer10set_boundsERKNS_4RectEb + 229
	4   QuartzCore                          0x00000001084ae4bd -[CALayer setBounds:] + 251
	5   UIKit                               0x000000010872d9b2 -[UIView(Geometry) setBounds:] + 539
	6   UIKit                               0x000000010875790a -[UIScrollView setBounds:] + 1140
	7   UIKit                               0x00000001087c23c6 -[UITableView setBounds:] + 283
	8   UIKit                               0x0000000108f67f3d -[UIPickerTableView setBounds:] + 122
	9   UIKit                               0x0000000108758b69 -[UIScrollView setContentOffset:] + 438
	10  UIKit                               0x00000001087c37ab -[UITableView setContentOffset:] + 310
	11  UIKit                               0x0000000108f672fc -[UIPickerTableView _setContentOffset:notify:] + 92
	12  UIKit                               0x00000001087767d6 -[UIScrollView(UIScrollViewInternal) _setContentOffset:animated:animationCurve:animationAdjustsForContentOffsetDelta:animation:] + 896
	13  UIKit                               0x0000000108f66491 -[UIPickerTableView _scrollRowAtIndexPathToSelectionBar:animated:] + 243
	14  UIKit                               0x0000000108f6683e -[UIPickerTableView selectRow:animated:notify:updateChecked:] + 760
	15  UIKit                               0x000000010865ff7b -[UIPickerView _selectRow:inComponent:animated:notify:] + 154
	16  Equiloco                            0x0000000104eaaecd -[IQDropDownTextField setSelectedRow:animated:] + 461
	17  Equiloco                            0x0000000104eaacf0 -[IQDropDownTextField setSelectedRow:] + 64
	18  Equiloco                            0x0000000104eab7c1 -[IQDropDownTextField setItemList:] + 161
	19  Equiloco                            0x0000000104f3058d -[UIHorseListNewHorseCell awakeFromNib] + 6477
	20  UIKit                               0x0000000108b0392d -[UINib instantiateWithOwner:options:] + 2413
	21  UIKit                               0x0000000108b0b1b9 -[NSBundle(UINSBundleAdditions) loadNibNamed:owner:options:] + 222
	22  Equiloco                            0x0000000104edacdb -[UIHorseListViewController tableView:cellForRowAtIndexPath:] + 1099
	23  UIKit                               0x00000001087d85c7 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 783
	24  UIKit                               0x00000001087d8b44 -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 74
	25  UIKit                               0x000000010879ff0a -[UITableView _updateVisibleCellsNow:isRecursive:] + 3168
	26  UIKit                               0x00000001087c0840 -[UITableView layoutSubviews] + 176
	27  UIKit                               0x000000010874a808 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1515
	28  QuartzCore                          0x00000001084b461a -[CALayer layoutSublayers] + 177
	29  QuartzCore                          0x00000001084b882b _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 395
	30  QuartzCore                          0x000000010843f29f _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 343
	31  QuartzCore                          0x000000010846c940 _ZN2CA11Transaction6commitEv + 568
	32  UIKit                               0x000000010867534f _UIApplicationFlushRunLoopCATransactionIfTooLate + 167
	33  UIKit                               0x0000000108fda532 __handleEventQueueInternal + 6875
	34  CoreFoundation                      0x0000000106f31bb1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	35  CoreFoundation                      0x0000000106f164af __CFRunLoopDoSources0 + 271
	36  CoreFoundation                      0x0000000106f15a6f __CFRunLoopRun + 1263
	37  CoreFoundation                      0x0000000106f1530b CFRunLoopRunSpecific + 635
	38  GraphicsServices                    0x000000010de2ba73 GSEventRunModal + 62
	39  UIKit                               0x000000010867b0b7 UIApplicationMain + 159
	40  Equiloco                            0x0000000104e7d1cf main + 111
	41  libdyld.dylib                       0x000000010b7f5955 start + 1
	42  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by sameer4** [comment] 2019-06-19 08:17
Happing a lot more in a new project @hackiftekhar 

> `*** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [0 nan; 320 291]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010579f6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000104d43ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010579f555 +[NSException raise:format:] + 197
	3   QuartzCore                          0x00000001046e84c8 _ZN2CA5Layer10set_boundsERKNS_4RectEb + 194
	4   QuartzCore                          0x00000001046d75fb -[CALayer setBounds:] + 254
	5   UIKitCore                           0x000000011056e5cd -[UIView(Geometry) setBounds:] + 414
	6   UIKitCore                           0x00000001105010c3 -[UIScrollView setBounds:] + 1071
	7   UIKitCore                           0x00000001102de7aa -[UITableView setBounds:] + 234
	8   UIKitCore                           0x0000000110049f5a -[UIPickerTableView setBounds:] + 109
	9   UIKitCore                           0x0000000110502333 -[UIScrollView setContentOffset:] + 509
	10  UIKitCore                           0x00000001102dfb58 -[UITableView setContentOffset:] + 311
	11  UIKitCore                           0x0000000110049370 -[UIPickerTableView _setContentOffset:notify:] + 92
	12  UIKitCore                           0x000000011051f57b -[UIScrollView(UIScrollViewInternal) _setContentOffset:animated:animationCurve:animationAdjustsForContentOffsetDelta:animation:] + 947
	13  UIKitCore                           0x00000001100485d7 -[UIPickerTableView _scrollRowAtIndexPathToSelectionBar:animated:] + 243
	14  UIKitCore                           0x0000000110048994 -[UIPickerTableView selectRow:animated:notify:updateChecked:] + 783
	15  UIKitCore                           0x0000000110052c92 -[UIPickerView _selectRow:inComponent:animated:notify:] + 154
	16  IQDropDownTextField                 0x0000000103f919d3 -[IQDropDownTextField setSelectedRow:animated:] + 467
	17  IQDropDownTextField                 0x0000000103f91f16 -[IQDropDownTextField setDropDownMode:] + 230
	18  Cycling                             0x0000000101996481 $s7Cycling23UIDropDownTextFieldCellC6config4data11enteredDatayAA012PopUpContentJ0C_10SwiftyJSON0O0VtF + 1393
	19  Cycling                             0x0000000101901446 $s7Cycling020UITableViewForPopUpsC10ControllerC05tableC0_04cellD5RowAtSo0bC4CellCSo0bC0C_10Foundation9IndexPathVtF + 3382
	20  Cycling                             0x0000000101902aab $s7Cycling020UITableViewForPopUpsC10ControllerC05tableC0_04cellD5RowAtSo0bC4CellCSo0bC0C_10Foundation9IndexPathVtFTo + 155
	21  UIKitCore                           0x00000001102f462c -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 764
	22  UIKitCore                           0x00000001102f4b65 -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 73
	23  UIKitCore                           0x00000001102bcd20 -[UITableView _updateVisibleCellsNow:isRecursive:] + 2870
	24  UIKitCore                           0x00000001102dce37 -[UITableView layoutSubviews] + 165
	25  UIKitCore                           0x00000001105899c1 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1417
	26  QuartzCore                          0x00000001046ddeae -[CALayer layoutSublayers] + 173
	27  QuartzCore                          0x00000001046e2b88 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 396
	28  QuartzCore                          0x00000001046eeee4 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 72
	29  QuartzCore                          0x000000010465e3aa _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 328
	30  QuartzCore                          0x0000000104695584 _ZN2CA11Transaction6commitEv + 608
	31  UIKitCore                           0x00000001100b5d8a _UIApplicationFlushRunLoopCATransactionIfTooLate + 150
	32  UIKitCore                           0x00000001101a8f5f __handleEventQueueInternal + 6845
	33  CoreFoundation                      0x0000000105706be1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	34  CoreFoundation                      0x0000000105706463 __CFRunLoopDoSources0 + 243
	35  CoreFoundation                      0x0000000105700b1f __CFRunLoopRun + 1231
	36  CoreFoundation                      0x0000000105700302 CFRunLoopRunSpecific + 626
	37  GraphicsServices                    0x00000001080132fe GSEventRunModal + 65
	38  UIKitCore                           0x00000001100bbba2 UIApplicationMain + 140
	39  Cycling                             0x00000001019afa6b main + 75
	40  libdyld.dylib                       0x000000010943f541 start + 1
	41  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by avikroy** [comment] 2019-11-13 14:37
Hi Team,
We are also getting similar kind of issue and this is random in nature.
Here is the crash log that we received:

CoreFoundation | __exceptionPreprocess + 228
-- | --
2 | libobjc.A.dylib | objc_exception_throw + 52
3 | CoreFoundation | +[NSException raise:format:] + 112
4 | QuartzCore | CA::Layer::set_bounds(CA::Rect const&, bool) + 164
5 | QuartzCore | -[CALayer setBounds:] + 136

**Comment by hackiftekhar** [comment] 2019-11-17 06:52
Hi guys, I've released v2.0 with some fixes related to row Index issues when user switching isOptionalDropDown to YES/NO. I have done couple of cleanups also but not sure if that fixes this problem since I do not know how to reproduce the issue.

**Comment by developerawais** [comment] 2019-12-04 08:03
Hi all,
This issue is resolved in v2.0.

**Comment by developerawais** [comment] 2019-12-05 06:36
<img width="1415" alt="Screenshot 2019-12-05 at 11 34 52 AM" src="https://user-images.githubusercontent.com/58505784/70210000-686e3980-1753-11ea-89c0-504c5c9d7ee4.png">

**Comment by hackiftekhar** [comment] 2019-12-18 16:08
Thanks @developerawais for letting me know. :)

**Closed by hackiftekhar** 2019-12-18 16:08 UTC
